### ISSUE TITLE
Documenting tracking down memory usage issues

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek-docs#102]
https://github.com/zeek/zeek/issues/1856 contains a lot of great information how to track down memory usage issues using jeprof and other tools. It would be good if this could be inserted into the docs somewhere as trouble-shooting steps users could follow if  they're encountering similar problems.

**Comment by awelzel** [comment]
@timwoj , do you think the new troubleshooting page enough pointers? Re-open if you think differently.
