### ISSUE TITLE
Pattern not support `{-}` and `{+}` operators

### ISSUE THREAD

**Issue by AmazingPP** [zeek/zeek-docs#149]
According to the [docs](https://docs.zeek.org/en/master/script-reference/types.html#type-pattern), Zeek accepts “patterns supported by the [flex lexical analyzer](http://westes.github.io/flex/manual/Patterns.html).”  However, character class unions/differences are not working. 

Running the following test-script with Zeek 5.0: 
```
const mypattern: pattern = /([[:print:]]{-}[[:alnum:]]foo)/;
```
Get the following error:
```
error in ././try.zeek, line 1: error compiling pattern /^?(.|\n)*(([[:print:]]{-}[[:alnum:]]foo))/
```

Reference to report on slack : https://zeekorg.slack.com/archives/CSZBXF6TH/p1662645132381609

**Comment by timwoj** [comment]
I transferred this over to the zeek-docs repo since it's more that our docs need to be updated to mention the two have diverged.
