### ISSUE TITLE
Missing trailing space in classic hexdump output

### ISSUE THREAD

**Issue by jsoref** [zeek/zeek-docs#158]
These two lines (195, 204) are missing a trailing space:
https://github.com/zeek/zeek-docs/blob/83aec92aa50d13a9eed3dd5f2aba2fc736ceb22b/logs/dpd.rst#L194-L196
https://github.com/zeek/zeek-docs/blob/83aec92aa50d13a9eed3dd5f2aba2fc736ceb22b/logs/dpd.rst#L203-L205

Referenced in: https://github.com/community/community/discussions/39336
Found using:
```
  [0-9A-FA-f]{4}.( \**[0-9a-f]{2}\**){16} {3}(?:.\**){16}
```

**Comment by ckreibich** [comment]
The final byte captured in the hexdump output is `0x20`, i.e., a space. It makes no difference whether we add a space to those lines or not.

**Comment by jsoref** [comment]
There's a difference between a space and nothing.
Hexdump and protocol tools try to be very careful about showing that distinction.

```sh
$ monitor() { x="$(echo -n "$1" | hexdump -C)"; echo "$x"; echo "$x"|wc; }
$ monitor "a"
00000000  61                                                |a|
00000001
       2       4      73
jsoref@jsoref-mbp argo-cd % monitor "a "
00000000  61 20                                             |a |
00000002
       2       6      74
```

(For reference, macOS appears to be using FreeBSD's hexdump.)

**Comment by ckreibich** [comment]
Thank you for educating me on the value of a hex dump. We're talking about documentation here, not the hexdump output in your shell pipeline. My point is that if you look at the rendered page ...

 https://docs.zeek.org/en/master/logs/dpd.html

... it makes no difference to readers of the docs. If you want to search for those particular lines with trailing whitespace in our documentation, you are free to do so. You'll be battling plenty of editing tools that complain about trailing whitespace in text files.

Please, let's move on.

**Comment by jsoref** [comment]
As it happens, `<pre>` tags *do* preserve trailing whitespace.

data:text/html,<pre>hello world%0d%0athis%20%0d%0athose%0d%0athem</pre>

For reference, my background is working on the Mozilla web browser for over a decade.

Yes, I'm aware you'd be fighting dumb text editors. Ideally a text editor would understand not to mess with content in `<pre>`, but whatever.

Thank you for educating me on the value of html and documentation.

I'll move on.

**Comment by timwoj** [comment]
To be honest, what probably happened here is someone (like me) opened this in a text editor that was configured to remove trailing spaces automatically on save (like mine is). So yah, probably my fault.
