### ISSUE TITLE
Issue when obtaining SSH sessions on LAN

### ISSUE THREAD

**Issue by tssingtampa** [zeek/zeek-docs#248]
I have configured zeek following the official documentation, then I have added redef to skip the checksum warning. I have configured the interface trying with different brands, I have done tcpdump and tshark and I don't see the ssh sessions except that of the same endpoint where I do the sniffing. I am connected to a mirror port.

Script
ssh_alerts.zeek

event connection_established(c: connection)
    {
    if (c$id$resp_p == 22/tcp)
        {
        print fmt("SSH Alerts: Con from %s a %s:%d",
                  c$id$orig_h, c$id$resp_h, c$id$resp_p);
        }
    }

![image](https://github.com/zeek/zeek-docs/assets/142441903/f9cee43d-320d-447c-97fb-3faaf5eba2f1)
![image](https://github.com/zeek/zeek-docs/assets/142441903/cd0512ab-8b97-4a0b-9cae-3ede5da561f9)
![image](https://github.com/zeek/zeek-docs/assets/142441903/922f0f7a-1f20-42f0-bed4-0b607d1fd82c)

/usr/local/zeek/etc/node.cfg
![image](https://github.com/zeek/zeek-docs/assets/142441903/b8f7e61a-92e3-4180-9d0c-977f44df587a)

/usr/local/zeek/share/zeek/site/local.zeek
![image](https://github.com/zeek/zeek-docs/assets/142441903/1e4b66f6-0d4d-4f8d-8123-a753added82f)

I hope soon your answer, greetings.

**Comment by bbannier** [comment]
We do not provide user support in issues in this repo. Questions like this are best answered using Slack, or our forum. Both of these are followed by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/
