### ISSUE TITLE
The INSTALL link appears to be broken

### ISSUE THREAD

**Issue by szaydel** [zeek/zeek-docs#254]
I just tried to `cat` the `INSTALL` file, which points to `doc/install.rst` and the link is broken, at least in the latest release and seemingly in master.
```
$ ls -l INSTALL
lrwxrwxrwx 1 root root 15 Mar 13 18:02 INSTALL -> doc/install.rst

$ file INSTALL
INSTALL: broken symbolic link to doc/install.rst
```

**EDIT:**
I just realized that I cannot even build from the source tarball, because it looks like submodule dependencies are not included in the tarball. This perhaps should be closed.

**Comment by JustinAzoff** [comment]
Hey Sam!

Yeah this is an issue with the auto generated tarballs.  If you look at https://github.com/zeek/zeek/releases/tag/v6.2.0 there's `zeek-6.2.0.tar.gz` which has all the required files, but the Autogenerated `Source code (tar.gz)` files only contain the toplevel repo and are basically broken.

Apparently there's no way to disable these and we aren't the only project that this causes issues with: https://github.com/orgs/community/discussions/6003

**Comment by szaydel** [comment]
Been a while @JustinAzoff! :) Thanks a lot for a quick response. I appreciate the pointer. I guess the link that zeek.org points to, ie: https://download.zeek.org/zeek-6.2.0.tar.gz is the same `zeek-6.2.0.tar.gz` that you pointed out.

Thanks a lot, Justin. I think we can probably close this one out!
