### ISSUE TITLE
RTD link for `lts` tag changed

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek-docs#284]
It looks like sometime around the release of `zeek-7.0.4` RTD now presents docs for the `lts` tag under [`lts_a`](https://docs.zeek.org/en/lts_a/) instead of just `lts`; the previous known and likely indexed [link](https://docs.zeek.org/en/lts/) disappeared and returns a `404`.

I tried rebuilding the `lts` docs (no success), and also a clean rebuild (deactivate tag to delete docs; add `lts` again and rebuild it; no success, link still under `lts_a`).

We should fix this soon as e.g., Google seems to index the `lts` docs and a search for `event zeek_init` has <https://docs.zeek.org/en/lts/scripts/base/bif/event.bif.zeek.html> as first hit. Once search engines realize the link is gone they will likely remove all references from their indices, and we would only appear after a reindex which could be weeks out.

**Comment by ckreibich** [comment]
Maybe related: https://github.com/readthedocs/readthedocs.org/issues/4062#issuecomment-387172117

> This is how rtd versions work: if you have a v0.8.3 branch and then you have a tag of the same name, rtd will create two versions 0.8.3 and 0.8.3_a. If you delete the branch/tag you just need to deactivate the version, then build the latest version to refresh the versions lists.

**Comment by bbannier** [comment]
FTR, I deactivated the `lts` version which according to the docs should delete it. I then reactivated it, but kept insisting on calling it `lts_a`.

**Comment by timwoj** [comment]
Same. I'll open a ticket with RTD because I'm clearly missing something here.

**Comment by ckreibich** [comment]
Looks like this is fixed. Good idea to try RTD's support route, Tim. Thanks!
