### ISSUE TITLE
typo in strftime

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/zeek-docs#31]
On page https://docs.zeek.org/en/current/examples/logs/index.html at the line just prior to section
`Using UIDs` there is reference to external documentation but it calls it: man strfime

**Comment by duffy-corelight** [comment]
Pull request is at https://github.com/duffy-corelight/zeek-docs/pull/1

**Comment by 0xxon** [comment]
You need to make the pull request against this repository - not your own one :).

(I will still pull it, but the way it currently is opened, it does not actually show up for us).

**Comment by duffy-corelight** [comment]
Thanks for the feedback. Still learning.
