### ISSUE TITLE
Capture CHANGES & NEWS in the documentation

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek-docs#61]
The docs currently do not contain release notes, so it's hard to figure out what's new in a recent release. We have release notes in CHANGES and NEWS, so we just need to explain their purpose and where to find them. (As far as I can tell the only way we currently involve those files is via redirects from older documentation that used to reside in the `/install` folder.)

**Comment by taosecurity** [comment]
I will cover this by adding a link as shown in https://zeek.org/get-zeek/ to the https://docs.zeek.org/en/lts/get-started.html section and tell people about examples like https://github.com/zeek/zeek/blob/v4.0.3/NEWS

**Comment by taosecurity** [comment]
I added the following to the end of quickstart.rst:

=== begin new content ===

* Track Zeek code releases by reading the "Release Notes" for each release.
  The "Get Zeek" web page points to this file for each new version of Zeek.
  These notes appear as the file NEWS, which summarizes the most important
  changes in the new version. For details on each change, see the separate
  CHANGES file, also accompanying each release.

=== end new content === 

As you can see, the use of "Release notes" which point to NEWS, and NEWS which summarize changes, and a third file actually called CHANGES, can be a bit confusing?

Incidentally I tried to attack my edited quickstart.rst to this entry, but Github doesn't support that. So, I zipped it.

[quickstart.zip](https://github.com/zeek/zeek-docs/files/6856034/quickstart.zip)
