### ISSUE TITLE
Documentation for new telemetry framework & Prometheus support

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek-docs#66]
This is the docs companion task to zeek/zeek#1491. @Neverlord already has great content here: https://github.com/zeek/zeek/wiki/Telemetry that we can use.

**Comment by rsmmr** [comment]
I'm thinking We could just stay with the Wiki page here for now because the primary, high-level  user-facing functionality isn't in place yet (i.e., a new telemetry framework). The Wiki page is also called out in NEWS now.
