### ISSUE TITLE
"vector of string" operations inadequately documented

### ISSUE THREAD

**Issue by vpax** [zeek/zeek-docs#67]
If https://docs.zeek.org/en/current/script-reference/types.html#vector is the definitive documentation for vectors, then as best as I can glean it doesn't describe which operations are allowed/not allowed on `vector of string`.  (I think all that's allowed for binary operations is `+`, which concatenates element-by-element.)

**Comment by ckreibich** [comment]
@rsmmr we felt like you should join in on the doc fun too. :-)

**Comment by rsmmr** [comment]
Will do (and will learn something :-)
