### ISSUE TITLE
Cover the new ability to specify a directory into which Zeek writes logs

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek-docs#70]
This is the docs counterpart to the technical work in zeek/zeek#1551. Could go into the framework docs or perhaps the logging format section.

**Comment by taosecurity** [comment]
Comment

**Comment by taosecurity** [comment]
I looked at this https://github.com/zeek/zeek-docs/commit/610486a460b62320d09b14729ff19805c538c6bc and I see commits to frameworks/logging.rst and quickstart.rst for the new options. I don't think I need to add anything else?

**Comment by timwoj** [comment]
Agreed, this looks done.
