### ISSUE TITLE
Cover the new attributes and new functionality relating to use defs 

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek-docs#72]
@vpax could you help me out here? Is the work of zeek/zeek#1394 at a point where you'd prefer to see it covered in the docs? I tagged it because it seemed that way, but I've not been following this closely. Thx.

**Comment by ckreibich** [comment]
(Similarly for the reaching definitions work of zeek/zeek#1376, thanks)

**Comment by vpax** [comment]
The part to document is the new `-u` flag (and its `-uu` variant), and the associated attributes.  I'll send you an `.md` starting point for this, derived from `README.ScriptOpt.USER.md` in `topic/vern/script-opt`.

**Comment by taosecurity** [comment]
Comment

**Comment by ckreibich** [comment]
I'll share Vern's existing documentation with you here, Richard.

**Comment by ckreibich** [comment]
@taosecurity, here's Vern's draft. I could see this going into the Basic Scripting section, for example. I noticed that this section only has one child node, `Introduction to Scripting` ... we may want to lift that up to be the name of the whole section — then it could also cover not-so-basic things.

[Usage.md](https://github.com/zeek/zeek-docs/files/6794178/Usage.md)
